{
 "title": "WebLogic Server Dashboard (JMX Exporter)",
 "description": "Weblogic Server Dashboard Using JMX Exporter Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(weblogic_server_listen_port, job)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(weblogic_server_listen_port{job=\"$job\"}, domain)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(weblogic_server_listen_port{domain=\"$domain\"}, server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JDK",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_join(jvm_info{job=\"$job\", domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Server Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_activation_time{domain=\"$domain\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 2 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_stable_state{domain=\"$domain\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_jvm_uptime{job=\"$job\", domain=\"$domain\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Deployed Applications",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(weblogic_application_webappcomponent_deployment_state{job=\"$job\",domain=\"$domain\", server=\"$server\"}) by (name))"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - weblogic_jvm_heap_free_percent{job=\"$job\", domain=\"$domain\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "JVM Current thread count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "repeat": "serverName",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_current{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 5 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblogic_server_open_sockets_current_count{job=\"$job\",domain=\"$domain\",server=\"$server\"}"
    }
   ]
  },
  {
   "title": "DS Wait For Connection",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 5 },
   "repeat": "serverName",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (weblogic_serverName) (weblogic_jdbcdatasource_waiting_for_connection_current_count{domain=\"$domain\",server=\"$server\"})",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Stuck thread",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(weblogic_threadpool_stuck_thread_count{domain=\"$domain\",server=~\"${server:regex}\"}) by (weblogic_threadpool_stuck_thread_count)"
    }
   ]
  },
  {
   "title": "Hogging thread",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(weblogic_threadpool_hogging_thread_count{domain=\"$domain\", server=~\"${server:regex}\"}) by (weblogic_workmanager_hogging_thread_count)"
    }
   ]
  },
  {
   "title": "JVM CPU usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(weblogic_system_cpu_load{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0) * 100"
    }
   ]
  },
  {
   "title": "Datasource Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_enabled{domain=\"$domain\",server=\"$server\"}"
    },
    {
     "expr": "weblogic_jdbcoracledatasource_waiting_for_connection_current_count{domain=\"$domain\",server=\"$server\"}"
    },
    {
     "expr": "irate(weblogic_jdbcoracledatasource_waiting_for_connection_failure_total{domain=\"$domain\",server=\"$server\"}[1m])"
    },
    {
     "expr": "irate(weblogic_jdbcoracledatasource_waiting_for_connection_success_total{domain=\"$domain\",server=\"$server\"}[1m])"
    },
    {
     "expr": "weblogic_jdbcoracledatasource_waiting_for_connection_failure_total{domain=\"$domain\",server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Applications Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "weblogic_application_webappcomponent_deployment_state{job=\"$job\", domain=\"$domain\", server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM heap used ({{server}})"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM heap committed ({{server}})"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM heap max size ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Non heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM non heap used ({{server}})"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM non heap commited ({{server}})"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "JVM non heap max ({{server}})"
    }
   ]
  },
  {
   "title": "JVM heap Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((jvm_memory_bytes_used{area=\"heap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0)/(jvm_memory_bytes_max{area=\"heap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0))*100",
     "legendFormat": "JVM heap used ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Non heap Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((jvm_memory_bytes_used{area=\"nonheap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0)/(jvm_memory_bytes_max{area=\"nonheap\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0))*100",
     "legendFormat": "JVM non heap used ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Code Cache Usage",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Code Heap non-nmethods Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 1, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"CodeHeap 'non-nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Eden Space"
    }
   ]
  },
  {
   "title": "Code Heap non-profiled nmethods Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"CodeHeap 'non-profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Eden Space"
    }
   ]
  },
  {
   "title": "Code Heap profiled nmethods Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"CodeHeap 'profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Eden Space"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-nmethod' Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"CodeHeap 'non-nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-nmethod' Used ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"CodeHeap 'non-nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-nmethod' Max ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"CodeHeap 'non-nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-nmethod' Commited ({{server}})"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-profiled nmethod' Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"CodeHeap 'non-profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-profiled nmethod' Used ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"CodeHeap 'non-profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-profiled nmethod' Max ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"CodeHeap 'non-profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'non-profiled nmethod' Commited ({{server}})"
    }
   ]
  },
  {
   "title": "CodeHeap 'profiled nmethod' Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"CodeHeap 'profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'profiled nmethod' Used ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"CodeHeap 'profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'profiled nmethod' Max ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"CodeHeap 'profiled nmethods'\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "CodeHeap 'profiled nmethod' Committed ({{server}})"
    }
   ]
  },
  {
   "title": "Yuong Gen",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Eden Space Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"G1 Eden Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Eden Space"
    }
   ]
  },
  {
   "title": "GC Pause Time Young GC (per 2 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",domain=\"$domain\"}[2m]) + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "{{gc}} ({{server}})"
    }
   ]
  },
  {
   "title": "GC count Young/per min ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",domain=\"$domain\"}[1m]) + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "{{gc}} ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "Java Heap: Young",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "G1 Survivor Space ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "G1 Eden Space ({{server}})"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "G1 Old Gen Init Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_init{pool=\"G1 Old Gen\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "jvm_memory_pool_bytes_commited{pool=\"G1 Old Gen\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0"
    }
   ]
  },
  {
   "title": "G1 Old Gen Max Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0"
    }
   ]
  },
  {
   "title": "GC Pause Time Old GC (per 2 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\",domain=\"$domain\"}[2m]) + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "{{gc}} ({{server}})"
    }
   ]
  },
  {
   "title": "GC count Old/per min ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\",domain=\"$domain\"}[1m]) + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "{{gc}} ({{server}})"
    }
   ]
  },
  {
   "title": "Java Heap: Old",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Old Gen ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Survivor Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Survivor Space ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"G1 Eden Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"$server\"}*0",
     "legendFormat": "G1 Eden Space ({{server}})"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total Class loaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Total Class loaded"
    }
   ]
  },
  {
   "title": "Total Class Unloaded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_unloaded_total{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Total Class Unloaded"
    }
   ]
  },
  {
   "title": "Current class loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Current Class loaded"
    }
   ]
  },
  {
   "title": "Java Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Metaspace ({{server}})"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Compressed Class Space ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Buffer Pool",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Buffer pool used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "{{pool}} Buffer pool used  ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Buffer pool capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "{{pool}} Buffer pool capacity  ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Buffer pool buffers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_buffers{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "{{pool}} Buffer pool buffers  ({{server}})"
    }
   ]
  },
  {
   "title": "JVM Thead Pool",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Thread Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "threads_current ({{server}})"
    },
    {
     "expr": "jvm_threads_daemon{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_daemon ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_threads_peak{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_peak ({{weblogic_serverName}})"
    },
    {
     "expr": "jvm_threads_deadlocked{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "threads_deadlock  ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "BLOCKED {{server}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "TIMED_WAITING {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"NEW\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "NEW {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"WAITING\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "WAITING {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "TERMINATED {{weblogic_serverName}}"
    },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\",weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "RUNNABLE {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(weblogic_system_cpu_load{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0)* 100",
     "legendFormat": " {{server}}"
    }
   ]
  },
  {
   "title": "Thread Pool Total Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_execute_thread_total_count{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Total Threads ({{server}})"
    },
    {
     "expr": "weblogic_threadpool_stuck_thread_count{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "Stuck Threads ({{server}})"
    },
    {
     "expr": "weblogic_threadpool_queue_length{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "queue"
    },
    {
     "expr": "weblogic_threadpool_hogging_thread_count{domain=\"$domain\"} + on(instance) group_left(server) weblogic_server_administration_port_enabled{server=\"${server:regex}\"}*0",
     "legendFormat": "hogging"
    }
   ]
  },
  {
   "title": "Web Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Sessions (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "topk(30,sum(weblogic_application_webappcomponent_sessions_opened_total_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Sessions Timeout (In Seconds) (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 115 },
   "targets": [
    {
     "expr": "topk(30,sum(weblogic_application_webappcomponent_session_timeout_secs{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Total Requests (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "topk(10,sum(weblogic_application_invocation_total_count{domain=\"$domain\",server=~\"${server:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Total Execution Time (top 10)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 115 },
   "targets": [
    {
     "expr": "topk(10,sum(weblogic_application_execution_time_total{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application))"
    }
   ]
  },
  {
   "title": "Current Sessions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(weblogic_application_webappcomponent_open_sessions_current_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Session Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_application_webappcomponent_sessions_opened_total_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}[5m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Execution Time per Request ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(weblogic_application_execution_time_total{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application)) / (sum(weblogic_application_invocation_total_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}) by (application))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_application_invocation_total_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}[5m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Weblogic Work Manager (WM)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stuck Thread Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_stuck_thread_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Hogging Thread Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_hogging_thread_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Completed requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_application_workmanager_completed_requests{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Pending requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_pending_requests{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "ThreadPool queue length Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_queue_length{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "ThreadPool Overload Rejected Requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 161 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_overload_rejected_requests_count{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "ThreadPool throughput Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_threadpool_throughput{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Completed daemon requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_completed_daemon_requests{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Pending daemon requests Weblogic WM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "weblogic_application_workmanager_pending_daemon_requests{job=\"$job\",domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{application}} | WM: {{name}} ({{server}})"
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {
     "expr": "sum(weblogic_jdbcoracledatasource_curr_capacity{domain=\"$domain\",server=~\"${server:regex}\"}) by (server,name)"
    },
    {
     "expr": "sum(weblogic_jdbcoracledatasource_active_connections_current_count{domain=\"$domain\",server=~\"${server:regex}\"}) by (server,name)"
    },
    {
     "expr": "sum(weblogic_jdbcoracledatasource_connections_total_count{domain=\"$domain\",server=~\"${server:regex}\"}) by (server,name)"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_active_connections_current_count{domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": " {{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Connection Request Failures (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_failed_reserve_request_count{domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": " {{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Datasource Waiting Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Requests that Waited (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 199 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_waiting_for_connection_total{domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Wait seconds high count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 199 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(weblogic_jdbcoracledatasource_wait_seconds_high_count{domain=\"$domain\",server=~\"${server:regex}\"}[$__range])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Connection Wait Successes (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_waiting_for_connection_success_total{domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Failed Waiting Connection Requests (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_waiting_for_connection_failure_total{domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Datasource Capacity",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_curr_capacity{domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "High num available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_highest_num_available{domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Active connections high count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_active_connections_high_count{domain=\"$domain\",server=~\"${server:regex}\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_connections_total_count{domain=\"$domain\",server=~\"${server:regex}\"}[1m])",
     "legendFormat": " {{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Datasource Prep Stmt Cache",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hit count prep stmt cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_prep_stmt_cache_hit_count{domain=\"$domain\",server=\"$server\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Miss count prep stmt cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_prep_stmt_cache_miss_count{domain=\"$domain\",server=\"$server\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Current prep stmt cache size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_prep_stmt_cache_current_size{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Access count prep stmt cache ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(weblogic_jdbcoracledatasource_prep_stmt_cache_access_count{domain=\"$domain\",server=\"$server\"}[1m])",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Leaked connection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_leaked_connection_count{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Total connection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 237 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_connections_total_count{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Waiting for Connection High Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 243 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_waiting_for_connection_high_count{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Waiting for Connection Current Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 243 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_waiting_for_connection_current_count{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": "{{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Connection delay time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_connection_delay_time{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": " {{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "Average Connection Delay Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 249 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "weblogic_jdbcoracledatasource_connection_delay_time{domain=\"$domain\",server=\"$server\"}",
     "legendFormat": " {{name}} @ {{server}}"
    }
   ]
  },
  {
   "title": "JMS Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JMS Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weblogic_jms_connections_current_count{domain=\"$domain\",server=\"$server\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "JMS Connection Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_jms_connections_total_count{domain=\"$domain\",server=\"$server\"}[5m])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "JMSServer Overview",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 262 },
   "targets": [
    {
     "expr": "sum(weblogic_jms_destinations_current_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)"
    },
    {
     "expr": "sum(weblogic_jms_messages_received_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)"
    },
    {
     "expr": "sum(weblogic_jms_bytes_received_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)"
    },
    {
     "expr": "sum(weblogic_jms_destinations_total_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)"
    },
    {
     "expr": "sum(weblogic_jms_destinations_current_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 266 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weblogic_jms_messages_current_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "sum(weblogic_jms_messages_pending_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 266 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weblogic_jms_bytes_current_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "sum(weblogic_jms_bytes_pending_count{domain=\"$domain\",server=~\"$server\"}) by (jmsserver)",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Received Message Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 273 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_jms_messages_received_count{domain=\"$domain\",server=~\"$server\"}[5m])) by (jmsserver)",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Received Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 273 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(weblogic_jms_bytes_received_count{domain=\"$domain\",server=~\"$server\"}[5m])) by (jmsserver)",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Destinations Overview",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 280 },
   "targets": [
    {
     "expr": "sum(weblogic_jms_dest_consumers_current_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_messages_current_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_messages_pending_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_bytes_current_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_bytes_pending_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_messages_received_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    },
    {
     "expr": "sum(weblogic_jms_dest_bytes_received_count{domain=\"$domain\",server=~\"$server\"}) by (destination)"
    }
   ]
  }
 ]
}