---
# In order to get WebLogic mbeans, you need to add the following options in server's options:
# -Djavax.management.builder.initial=weblogic.management.jmx.mbeanserver.WLSMBeanServerBuilder

attrNameSnakeCase: true
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "java.lang:type=OperatingSystem"
  - "com.bea:ServerRuntime=*,Name=*,Type=JVMRuntime"
  #- "com.bea:Name=*,Type=Domain"
  - "com.bea:Name=*,Type=ServerRuntime"
  - "com.bea:ServerRuntime=*,Type=ApplicationRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JDBCOracleDataSourceRuntime,*"
  - "com.bea:ServerRuntime=*,Type=ThreadPoolRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JMSRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JMSServerRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JMSDestinationRuntime,*"
  - "com.bea:ServerRuntime=*,Type=SAFRuntime,*"
  - "com.bea:ServerRuntime=*,Type=WorkManagerRuntime,*"
  - "com.bea:ServerRuntime=*,Type=PersistentStoreRuntime,*"
  - "com.bea:ServerRuntime=*,Type=WebAppComponentRuntime,*"
  - "com.bea:ServerRuntime=*,Type=ServletRuntime,*"


rules:
  #com.bea<ServerRuntime=AdminServer, Name=AdminServer_/bea_wls_internal, ApplicationRuntime=bea_wls_internal, Type=WebAppComponentRuntime><>SessionsOpenedTotalCount)
  # com.bea<ServerRuntime=AdminServer, Name=ClientClose, ApplicationRuntime=bea_wls_internal, Type=ServletRuntime, WebAppComponentRuntime=AdminServer_/bea_wls_internal><>ExecutionTimeTotal
  - pattern: "^com.bea<ServerRuntime=(.+), Name=(.+), (.+)Runtime=(.*), Type=ServletRuntime, WebAppComponentRuntime=(.+)><>(.+):"
    name: weblogic_$3_$6
    attrNameSnakeCase: true
    labels:
      server: $1
      name: $2
      application: $4

  # ex: java.lang<type=OperatingSystem><>ProcessCpuTime
  - pattern: "^java.lang<type=OperatingSystem><>(.+):"
    name: weblogic_$1
    attrNameSnakeCase: true

 # ex: com.bea<Name=Server-0, Type=ServerRuntime><>StableState
  - pattern: "^com.bea<Name=(.+), Type=(.+)Runtime><>(.+):"
    name: weblogic_$2_$3
    attrNameSnakeCase: true
    labels:
      server: $1

 # com.bea<ServerRuntime=AdminServer, Name=ClientClose, ApplicationRuntime=bea_wls_internal, Type=ServletRuntime, WebAppComponentRuntime=AdminServer_/bea_wls_internal><>InvocationTotalCount
  # ex: com.bea<ServerRuntime=AdminServer, Name=default, ApplicationRuntime=moduleJMS, Type=WorkManagerRuntime><>CompletedRequests
  - pattern: "^com.bea<ServerRuntime=(.+), Name=(.+), (.+)Runtime=(.*), Type=(.+)Runtime><>(.+):"
    name: weblogic_$3_$5_$6
    attrNameSnakeCase: true
    labels:
      server: $1
      name: $2
      application: $4

  # ex: com.bea<ServerRuntime=Server, Name=dsName, Type=JDBCOracleDataSourceRuntime><>Metric // we have to use JDBCOracleDataSource in case of therap
  - pattern: "^com.bea<ServerRuntime=(.+), Name=(.+), Type=JDBCOracleDataSourceRuntime><>(.+):"
    name: weblogic_jdbcoracledatasource_$3
    attrNameSnakeCase: true
    labels:
      server: $1
      name: $2

  # ex: com.bea<ServerRuntime=AdminServer, Name=bea_wls_cluster_internal, Type=ApplicationRuntime><OverallHealthStateJMX>IsCritical
  - pattern: "^com.bea<ServerRuntime=(.+), Name=(.+), Type=(.+)Runtime><(.+)>(.+):"
    name: weblogic_$3_$4_$5
    attrNameSnakeCase: true
    labels:
      runtime: $1
      name: $2

# uncomment this to fetch domain name from mbeans
#  - pattern: "^com.bea<Name=(.*), Type=Domain><>(id): (.+)"
#    name: weblogic_id
#    attrNameSnakeCase: true
#    labels:
#      domain: $1